global using Grpc.Core;
global using Grpc.Core.Interceptors;
global using Grpc.Net.Client;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Http;
global using Polly;
global using Polly.CircuitBreaker;
global using Polly.Retry;
global using Polly.Timeout;
